version: '3'

services:
    app:
        build:
            context: app
            args:
                NODE_VERSION: ${NODE_VERSION}
        container_name: peraklad_app
        tty: true
        stdin_open: true
        ports:
            - 8889:8888
            - 4001:4000
            - 3001:3000
        volumes:
            - ./app/www/:/var/www/html/:rw
        environment:
            - NEO4J_URI=${NEO4J_URI}
            - NEO4J_USER=${NEO4J_USER}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}
            - NEO4J_DATABASE=${NEO4J_DATABASE}
            - NEO4J_ENCRYPTED=${NEO4J_ENCRYPTED}
            - LOCALE=${LOCALE}
            - OMDB_API_KEY=${OMDB_API_KEY}
            - NODE_ENV=${NODE_ENV}
            - OPENSUBTITLES_UA=${OPENSUBTITLES_UA}
            - OPENSUBTITLES_USERNAME=${OPENSUBTITLES_USERNAME}
            - OPENSUBTITLES_PASSWORD=${OPENSUBTITLES_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
            - MY_AWS_ACCESS_KEY=${MY_AWS_ACCESS_KEY}
            - MY_AWS_ACCESS_KEY_SECRET=${MY_AWS_ACCESS_KEY_SECRET}
            - S3_BUCKET_RESOURCE=${S3_BUCKET_RESOURCE}
            - S3_BUCKET_AUTONOMY_WORK=${S3_BUCKET_AUTONOMY_WORK}
            - S3_BUCKET_POSTER=${S3_BUCKET_POSTER}
            - SMTP_MAIL=${SMTP_MAIL}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - MAIN_URL=${MAIN_URL}
            - SMS_API_KEY=${SMS_API_KEY}
            - SMS_API_SECRET=${SMS_API_SECRET}
            - REACT_APP_API_URL=${REACT_APP_API_URL}
            - REACT_APP_MAIN_URL=${REACT_APP_MAIN_URL}
            - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
            - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
            - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
            - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
        depends_on:
            - db

    db:
        build:
            context: db
        container_name: peraklad_db
        tty: true
        stdin_open: true
        restart: unless-stopped
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./db/dbms/data:/data
            - ./db/dbms/logs:/logs
            - ./db/operations/apoc.conf:/conf/apoc.conf
        environment:
            - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_dbms_default__database=${NEO4J_DATABASE}
            - NEO4J_dbms_memory_pagecache_size=${MEMORY_PAGECACHE_SIZE}
            - NEO4J_dbms_memory_heap_initial__size=${MEMORY_HEAP_INITIAL_SIZE}
            - NEO4J_dbms_memory_heap_max__size=${MEMORY_HEAP_MAX_SIZE}
